[package]
name = "blog_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.8"
dotenvy = "0.15.6"
sea-orm = { version = "0.11.0", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
